

services:
  db:
    image: mysql:8
    environment:
      MYSQL_USER : weather
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: weather_app
    ports:
      - "3306:3307"
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend Spring Boot
  backend:
    build: ./backend
    container_name: weather_backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/weather_app
      SPRING_DATASOURCE_USERNAME: weather
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    networks:
      - app-network

  # Frontend Nginx
  frontend:
    build: ./frontend
    container_name: weather_frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge